/*
 LaziestLoader - v0.5.1 - 2014-06-19
 A responsive lazy loader for jQuery.
 http://sjwilliams.github.io/laziestloader/
 Copyright (c) 2014 Josh Williams; Licensed MIT
*/
(function(c,e,g,l){var a=c(e);c.fn.lazyload=function(b){function d(){var a=0;f.each(function(){var b=c(this);if(!(h.skip_invisible&&!b.is(":visible")||c.abovethetop(this,h)||c.leftofbegin(this,h)))if(!c.belowthefold(this,h)&&!c.rightoffold(this,h))b.trigger("appear"),a=0;else if(++a>h.failure_limit)return!1})}var f=this,m,h={threshold:0,failure_limit:0,event:"scroll",effect:"show",container:e,data_attribute:"original",skip_invisible:!0,appear:null,load:null};return b&&(l!==b.failurelimit&&(b.failure_limit=
b.failurelimit,delete b.failurelimit),l!==b.effectspeed&&(b.effect_speed=b.effectspeed,delete b.effectspeed),c.extend(h,b)),m=h.container===l||h.container===e?a:c(h.container),0===h.event.indexOf("scroll")&&m.bind(h.event,function(a){return d()}),this.each(function(){var a=this,b=c(a);a.loaded=!1;b.one("appear",function(){this.loaded||(h.appear&&h.appear.call(a,f.length,h),c("<img />").bind("load",function(){b.hide().attr("src",b.data(h.data_attribute))[h.effect](h.effect_speed);a.loaded=!0;var d=
c.grep(f,function(a){return!a.loaded});f=c(d);h.load&&h.load.call(a,f.length,h)}).attr("src",b.data(h.data_attribute)))});0!==h.event.indexOf("scroll")&&b.bind(h.event,function(d){a.loaded||b.trigger("appear")})}),a.bind("resize",function(a){d()}),/iphone|ipod|ipad.*os 5/gi.test(navigator.appVersion)&&a.bind("pageshow",function(a){a.originalEvent.persisted&&f.each(function(){c(this).trigger("appear")})}),c(e).load(function(){d()}),this};c.belowthefold=function(b,d){var f;return d.container===l||d.container===
e?f=a.height()+a.scrollTop():f=c(d.container).offset().top+c(d.container).height(),f<=c(b).offset().top-d.threshold};c.rightoffold=function(b,d){var f;return d.container===l||d.container===e?f=a.width()+a.scrollLeft():f=c(d.container).offset().left+c(d.container).width(),f<=c(b).offset().left-d.threshold};c.abovethetop=function(b,d){var f;return d.container===l||d.container===e?f=a.scrollTop():f=c(d.container).offset().top,f>=c(b).offset().top+d.threshold+c(b).height()};c.leftofbegin=function(b,d){var f;
return d.container===l||d.container===e?f=a.scrollLeft():f=c(d.container).offset().left,f>=c(b).offset().left+d.threshold+c(b).width()};c.inviewport=function(a,d){return!c.rightoffold(a,d)&&!c.leftofbegin(a,d)&&!c.belowthefold(a,d)&&!c.abovethetop(a,d)};c.extend(c.expr[":"],{"below-the-fold":function(a){return c.belowthefold(a,{threshold:0})},"above-the-top":function(a){return!c.belowthefold(a,{threshold:0})},"right-of-screen":function(a){return c.rightoffold(a,{threshold:0})},"left-of-screen":function(a){return!c.rightoffold(a,
{threshold:0})},"in-viewport":function(a){return c.inviewport(a,{threshold:0})},"above-the-fold":function(a){return!c.belowthefold(a,{threshold:0})},"right-of-fold":function(a){return c.rightoffold(a,{threshold:0})},"left-of-fold":function(a){return!c.rightoffold(a,{threshold:0})}})})(jQuery,window,document);
!function(c){"function"==typeof define&&define.amd?define(["jquery"],c):c(jQuery)}(function(c){var e=function(g,l){function a(a){a.addClass("ll-loaded").removeClass("ll-notloaded");a.trigger("loaded");"function"==typeof l&&l.call(a)}function b(){h.one("laziestloader",function(){var b,d=c(this);d.data().ratio&&f.call(this);g.setSourceMode&&(b=g.getSource(d),b&&this.getAttribute("src")!==b&&this.setAttribute("src",b));!g.setSourceMode||"IMG"!==this.nodeName&&"VIDEO"!==this.nodeName&&"AUDIO"!==this.nodeName?
a(d):"IMG"===this.nodeName?this.onload=function(){a(d)}:this.onloadstart=function(){a(d)}})}function d(){var a=h.not(p).filter(function(){var a=c(this),b=g.threshold;if(!a.is(":hidden")){var d=m.scrollTop(),f=d+m.height(),h=a.offset().top;return h+a.height()>=d-b&&f+b>=h}});a.trigger("laziestloader");p.add(a)}function f(){var a=c(this),b=a.data();b.ratio=b.ratio||b.heightMultiplier;b.ratio&&a.css({height:Math.round(a.width()*b.ratio)})}var m=c(window),h=this,p=c(),k=1<window.devicePixelRatio,n=!1;
g=c.extend(!0,{threshold:0,sizePattern:/{{SIZE}}/gi,getSource:function(a){var b,d,f=a.data();return f.pattern&&f.widths&&c.isArray(f.widths)?(b=k?f.patternRetina:f.pattern,b=b||f.pattern,"object"==typeof f.widths[0]?(d=function(){for(var b=c.map(f.widths,function(a){return a.size}),b=q(a.width(),b),d=f.widths.length-1;0<=d;d--)if(f.widths[d].size===b)return f.widths[d].slug}(),b=b.replace(g.sizePattern,d)):b=b.replace(g.sizePattern,q(a.width(),f.widths))):(b=k?f.srcRetina:f.src,b=b||f.src),b},scrollThrottle:250,
sizeOffsetPercent:0,setSourceMode:!0},g);var q=e.bestFit=function(a,b){var d=b[b.length-1],f=b.length,c=g.sizeOffsetPercent/100*a;for(b.sort(function(a,b){return a-b});f--;)a-c<=b[f]&&(d=b[f]);return d};return h.addClass("ll-init ll-notloaded").each(f),b(),m.scroll(function(){n=!0}),setInterval(function(){n&&(n=!1,d())},g.scrollThrottle),m.resize(function(){p=c();h.off("laziestloader");b();d()}),d(),this};c.fn.laziestloader=e});
!function(c){"function"==typeof define&&define.amd?define(["jquery"],c):"object"==typeof exports?c(require("jquery")):c(jQuery)}(function(c){function e(b){b=a.json?JSON.stringify(b):String(b);return a.raw?b:encodeURIComponent(b)}function g(b,d){var f;if(a.raw)f=b;else a:{var e=b;0===e.indexOf('"')&&(e=e.slice(1,-1).replace(/\\"/g,'"').replace(/\\\\/g,"\\"));try{f=(e=decodeURIComponent(e.replace(l," ")),a.json?JSON.parse(e):e);break a}catch(h){}f=void 0}return c.isFunction(d)?d(f):f}var l=/\+/g,a=
c.cookie=function(b,d,f){if(void 0!==d&&!c.isFunction(d)){if(f=c.extend({},a.defaults,f),"number"==typeof f.expires){var m=f.expires,h=f.expires=new Date;h.setTime(+h+864E5*m)}return document.cookie=[a.raw?b:encodeURIComponent(b),"=",e(d),f.expires?"; expires="+f.expires.toUTCString():"",f.path?"; path="+f.path:"",f.domain?"; domain="+f.domain:"",f.secure?"; secure":""].join("")}f=b?void 0:{};for(var m=document.cookie?document.cookie.split("; "):[],h=0,p=m.length;p>h;h++){var k=m[h].split("="),n;
n=k.shift();n=a.raw?n:decodeURIComponent(n);k=k.join("=");if(b&&b===n){f=g(k,d);break}b||void 0===(k=g(k))||(f[n]=k)}return f};a.defaults={};c.removeCookie=function(a,d){return void 0===c.cookie(a)?!1:(c.cookie(a,"",c.extend({},d,{expires:-1})),!c.cookie(a))}});(function(){var c=[].indexOf||function(c){for(var e=0,a=this.length;e<a;e++)if(e in this&&this[e]===c)return e;return-1},e=[].slice;(function(c,e){return"function"===typeof define&&define.amd?define("waypoints",["jquery"],function(a){return e(a,c)}):e(c.jQuery,c)})(window,function(g,l){var a,b,d,f,m,h,p,k,n,q;a=g(l);p=0<=c.call(l,"ontouchstart");f={horizontal:{},vertical:{}};m=1;h={};q=1;b=function(){function a(b){var d=this;this.$element=b;this.element=b[0];this.didScroll=this.didResize=!1;this.id=
"context"+m++;this.oldScroll={x:b.scrollLeft(),y:b.scrollTop()};this.waypoints={horizontal:{},vertical:{}};this.element["waypoints-context-id"]=this.id;h[this.id]=this;b.bind("scroll.waypoints",function(){if(!d.didScroll&&!p)return d.didScroll=!0,l.setTimeout(function(){d.doScroll();return d.didScroll=!1},g.waypoints.settings.scrollThrottle)});b.bind("resize.waypoints",function(){if(!d.didResize)return d.didResize=!0,l.setTimeout(function(){g.waypoints("refresh");return d.didResize=!1},g.waypoints.settings.resizeThrottle)})}
a.prototype.doScroll=function(){var a,b=this;a={horizontal:{newScroll:this.$element.scrollLeft(),oldScroll:this.oldScroll.x,forward:"right",backward:"left"},vertical:{newScroll:this.$element.scrollTop(),oldScroll:this.oldScroll.y,forward:"down",backward:"up"}};!p||a.vertical.oldScroll&&a.vertical.newScroll||g.waypoints("refresh");g.each(a,function(a,d){var f,c,h;h=[];f=(c=d.newScroll>d.oldScroll)?d.forward:d.backward;g.each(b.waypoints[a],function(a,b){var f,c;if(d.oldScroll<(f=b.offset)&&f<=d.newScroll||
d.newScroll<(c=b.offset)&&c<=d.oldScroll)return h.push(b)});h.sort(function(a,b){return a.offset-b.offset});c||h.reverse();return g.each(h,function(a,b){if(b.options.continuous||a===h.length-1)return b.trigger([f])})});return this.oldScroll={x:a.horizontal.newScroll,y:a.vertical.newScroll}};a.prototype.refresh=function(){var a,b,d=this;b=g.isWindow(this.element);a=this.$element.offset();this.doScroll();a={horizontal:{contextOffset:b?0:a.left,contextScroll:b?0:this.oldScroll.x,contextDimension:this.$element.width(),
oldScroll:this.oldScroll.x,forward:"right",backward:"left",offsetProp:"left"},vertical:{contextOffset:b?0:a.top,contextScroll:b?0:this.oldScroll.y,contextDimension:b?g.waypoints("viewportHeight"):this.$element.height(),oldScroll:this.oldScroll.y,forward:"down",backward:"up",offsetProp:"top"}};return g.each(a,function(a,b){return g.each(d.waypoints[a],function(a,d){var f,c,h,e,p;f=d.options.offset;h=d.offset;c=g.isWindow(d.element)?0:d.$element.offset()[b.offsetProp];g.isFunction(f)?f=f.apply(d.element):
"string"===typeof f&&(f=parseFloat(f),-1<d.options.offset.indexOf("%")&&(f=Math.ceil(b.contextDimension*f/100)));d.offset=c-b.contextOffset+b.contextScroll-f;if((!d.options.onlyOnScroll||null==h)&&d.enabled){if(null!==h&&h<(e=b.oldScroll)&&e<=d.offset)return d.trigger([b.backward]);if(null!==h&&h>(p=b.oldScroll)&&p>=d.offset||null===h&&b.oldScroll>=d.offset)return d.trigger([b.forward])}})})};a.prototype.checkEmpty=function(){if(g.isEmptyObject(this.waypoints.horizontal)&&g.isEmptyObject(this.waypoints.vertical))return this.$element.unbind("resize.waypoints scroll.waypoints"),
delete h[this.id]};return a}();d=function(){function a(b,d,c){var h;"bottom-in-view"===c.offset&&(c.offset=function(){var a;a=g.waypoints("viewportHeight");g.isWindow(d.element)||(a=d.$element.height());return a-g(this).outerHeight()});this.$element=b;this.element=b[0];this.axis=c.horizontal?"horizontal":"vertical";this.callback=c.handler;this.context=d;this.enabled=c.enabled;this.id="waypoints"+q++;this.offset=null;this.options=c;d.waypoints[this.axis][this.id]=this;f[this.axis][this.id]=this;b=
null!=(h=this.element["waypoints-waypoint-ids"])?h:[];b.push(this.id);this.element["waypoints-waypoint-ids"]=b}a.prototype.trigger=function(a){if(this.enabled&&(null!=this.callback&&this.callback.apply(this.element,a),this.options.triggerOnce))return this.destroy()};a.prototype.disable=function(){return this.enabled=!1};a.prototype.enable=function(){this.context.refresh();return this.enabled=!0};a.prototype.destroy=function(){delete f[this.axis][this.id];delete this.context.waypoints[this.axis][this.id];
return this.context.checkEmpty()};a.getWaypointsByElement=function(a){var b;a=a["waypoints-waypoint-ids"];if(!a)return[];b=g.extend({},f.horizontal,f.vertical);return g.map(a,function(a){return b[a]})};return a}();n={init:function(a,f){f=g.extend({},g.fn.waypoint.defaults,f);null==f.handler&&(f.handler=a);this.each(function(){var a,c,e;a=g(this);e=null!=(c=f.context)?c:g.fn.waypoint.defaults.context;g.isWindow(e)||(e=a.closest(e));e=g(e);(c=h[e[0]["waypoints-context-id"]])||(c=new b(e));return new d(a,
c,f)});g.waypoints("refresh");return this},disable:function(){return n._invoke.call(this,"disable")},enable:function(){return n._invoke.call(this,"enable")},destroy:function(){return n._invoke.call(this,"destroy")},prev:function(a,b){return n._traverse.call(this,a,b,function(a,b,d){if(0<b)return a.push(d[b-1])})},next:function(a,b){return n._traverse.call(this,a,b,function(a,b,d){if(b<d.length-1)return a.push(d[b+1])})},_traverse:function(a,b,d){var f,c;null==a&&(a="vertical");null==b&&(b=l);c=k.aggregate(b);
f=[];this.each(function(){var b;b=g.inArray(this,c[a]);return d(f,b,c[a])});return this.pushStack(f)},_invoke:function(a){this.each(function(){var b;b=d.getWaypointsByElement(this);return g.each(b,function(b,d){d[a]();return!0})});return this}};g.fn.waypoint=function(){var a,b;b=arguments[0];a=2<=arguments.length?e.call(arguments,1):[];return n[b]?n[b].apply(this,a):g.isFunction(b)?n.init.apply(this,arguments):g.isPlainObject(b)?n.init.apply(this,[null,b]):b?g.error("The "+b+" method does not exist in jQuery Waypoints."):
g.error("jQuery Waypoints needs a callback function or handler option.")};g.fn.waypoint.defaults={context:l,continuous:!0,enabled:!0,horizontal:!1,offset:0,triggerOnce:!1};k={refresh:function(){return g.each(h,function(a,b){return b.refresh()})},viewportHeight:function(){var b;return null!=(b=l.innerHeight)?b:a.height()},aggregate:function(a){var b,d,c;b=f;a&&(b=null!=(c=h[g(a)[0]["waypoints-context-id"]])?c.waypoints:void 0);if(!b)return[];d={horizontal:[],vertical:[]};g.each(d,function(a,f){g.each(b[a],
function(a,b){return f.push(b)});f.sort(function(a,b){return a.offset-b.offset});d[a]=g.map(f,function(a){return a.element});return d[a]=g.unique(d[a])});return d},above:function(a){null==a&&(a=l);return k._filter(a,"vertical",function(a,b){return b.offset<=a.oldScroll.y})},below:function(a){null==a&&(a=l);return k._filter(a,"vertical",function(a,b){return b.offset>a.oldScroll.y})},left:function(a){null==a&&(a=l);return k._filter(a,"horizontal",function(a,b){return b.offset<=a.oldScroll.x})},right:function(a){null==
a&&(a=l);return k._filter(a,"horizontal",function(a,b){return b.offset>a.oldScroll.x})},enable:function(){return k._invoke("enable")},disable:function(){return k._invoke("disable")},destroy:function(){return k._invoke("destroy")},extendFn:function(a,b){return n[a]=b},_invoke:function(a){var b;b=g.extend({},f.vertical,f.horizontal);return g.each(b,function(b,d){d[a]();return!0})},_filter:function(a,b,d){var f,c;f=h[g(a)[0]["waypoints-context-id"]];if(!f)return[];c=[];g.each(f.waypoints[b],function(a,
b){if(d(f,b))return c.push(b)});c.sort(function(a,b){return a.offset-b.offset});return g.map(c,function(a){return a.element})}};g.waypoints=function(){var a,b;b=arguments[0];a=2<=arguments.length?e.call(arguments,1):[];return k[b]?k[b].apply(null,a):k.aggregate.call(null,b)};g.waypoints.settings={resizeThrottle:100,scrollThrottle:30};return a.on("load.waypoints",function(){return g.waypoints("refresh")})})}).call(this);$(function(){(function(c,e){window.epochload?epochload.push(function(){add_lazy_load_section(c,e)}):e()})("#below_article_ad",function(){$("#comment_box").prepend("<script type='text/javascript'>var aid = 0;var encoding = '';var badcaptcha=false;\x3c/script><script type='text/javascript' src='http://comments.epochtimes.com/js/articlecomments.js'>\x3c/script>")})});
genQRcode=function(c){size=200;chart="http://chart.googleapis.com/chart?cht=qr&chs="+size+"x"+size+"&choe=UTF-8&chld=L|0&chl="+c;$("#wechat-content").show();document.getElementById("qrcode").src=chart};hideQRcode=function(){$("#wechat-content").hide()};function changeArticleFont(c){var e=document.getElementById("artbody");switch(c){case "s":e.style.fontSize="9pt";break;case "m":e.style.fontSize="12pt";break;case "b":e.style.fontSize="15pt";break;default:e.style.fontSize="12pt"}}
function anc(){var c=/n([0-9]+).htm/.exec(window.location.href),e="";null!=c&&(e=c[1]);var g=Math.floor(1000001*Math.random());$.get("/anc/bridge.htm",{general:e+"a"+g},function(){});$("div.anc").each(function(){""!=e&&$(this).find("a").each(function(){var c=$(this).attr("href")+"?show=anc&region=article&hash="+e+"a"+g;$(this).attr("href",c)})})}
(function(c,e){window.epochload?epochload.push(function(){add_lazy_load_section(c,e)}):e()})("h1",function(){function c(c){c&&(c.target&&"IFRAME"==c.target.nodeName&&((c=c.target.src)?(c=/[\?&#]url=([^&#]*)/.exec(c),opt_target=null!=c?unescape(c[1]):void 0):opt_target=void 0),ga("send","social","twitter","tweet",void 0))}(function(c,g,l){var a=c.getElementsByTagName(g)[0];c.getElementById(l)||(c=c.createElement(g),c.id=l,c.async="true",c.src="//connect.facebook.net/zh_TW/sdk.js#xfbml=1&version=v2.3&appId=117423058344194",
a.parentNode.insertBefore(c,a))})(document,"script","facebook-jssdk");window.twttr=function(c,g,l){var a,b=c.getElementsByTagName(g)[0],d=/^http:/.test(c.location)?"http":"https";if(!c.getElementById(l))return c=c.createElement(g),c.id=l,c.async="true",c.src=d+"://platform.twitter.com/widgets.js",b.parentNode.insertBefore(c,b),window.twttr||(a={_e:[],ready:function(b){a._e.push(b)}})}(document,"script","twitter-wjs");twttr.ready(function(e){e.events.bind("tweet",c)});$("body").append("<script src='https://apis.google.com/js/platform.js' async defer>{lang: 'zh-TW'}\x3c/script><script src='//platform.linkedin.com/in.js' type='text/javascript' async> lang: zh-TW\x3c/script>")});
(function(c,e){window.epochload?epochload.push(function(){add_lazy_load_section(c,e)}):e()})("#below_article_ad",function(){FB.Event.subscribe("message.send",function(c){ga("send","social","Facebook","share",c)})});(function(c,e,g,l){(function(a){for(var b=a.length,d=c("head");b--;)0===d.has("."+a[b]).length&&d.append('<meta class="'+a[b]+'" />')})("foundation-mq-small foundation-mq-small-only foundation-mq-medium foundation-mq-medium-only foundation-mq-large foundation-mq-large-only foundation-mq-xlarge foundation-mq-xlarge-only foundation-mq-xxlarge foundation-data-attribute-namespace".split(" "));c(function(){"undefined"!==typeof FastClick&&"undefined"!==typeof g.body&&FastClick.attach(g.body)});var a=function(a,
b){if("string"===typeof a){if(b){var d;if(b.jquery){if(d=b[0],!d)return b}else d=b;return c(d.querySelectorAll(a))}return c(g.querySelectorAll(a))}return c(a,b)},b=function(a){var b=[];a||b.push("data");0<this.namespace.length&&b.push(this.namespace);b.push(this.name);return b.join("-")},d=function(a){a=a.split("-");for(var b=a.length,d=[];b--;)0!==b?d.push(a[b]):0<this.namespace.length?d.push(this.namespace,a[b]):d.push(a[b]);return d.reverse().join("-")},f=function(b,d){var f=this,e=!a(this).data(this.attr_name(!0));
a(this.scope).is("["+this.attr_name()+"]")?(a(this.scope).data(this.attr_name(!0)+"-init",c.extend({},this.settings,d||b,this.data_options(a(this.scope)))),e&&this.events(this.scope)):a("["+this.attr_name()+"]",this.scope).each(function(){var e=!a(this).data(f.attr_name(!0)+"-init");a(this).data(f.attr_name(!0)+"-init",c.extend({},f.settings,d||b,f.data_options(a(this))));e&&f.events(this)});if("string"===typeof b)return this[b].call(this,d)},m=function(a,b){function d(){b(a[0])}function f(){this.one("load",
d);if(/MSIE (\d+\.\d+);/.test(navigator.userAgent)){var a=this.attr("src"),b=a.match(/\?/)?"&":"?",b=b+("random="+(new Date).getTime());this.attr("src",a+b)}}a.attr("src")?a[0].complete||4===a[0].readyState?d():f.call(a):d()};e.matchMedia=e.matchMedia||function(a){var b,d=a.documentElement,f=d.firstElementChild||d.firstChild,c=a.createElement("body"),e=a.createElement("div");e.id="mq-test-1";e.style.cssText="position:absolute;top:-100em";c.style.background="none";c.appendChild(e);return function(a){e.innerHTML=
'&shy;<style media="'+a+'"> #mq-test-1 { width: 42px; }</style>';d.insertBefore(c,f);b=42===e.offsetWidth;d.removeChild(c);return{matches:b,media:a}}}(g);(function(a){function b(){d&&(c(b),g&&jQuery.fx.tick())}var d,f=0;a=["webkit","moz"];for(var c=e.requestAnimationFrame,m=e.cancelAnimationFrame,g="undefined"!==typeof jQuery.fx;f<a.length&&!c;f++)c=e[a[f]+"RequestAnimationFrame"],m=m||e[a[f]+"CancelAnimationFrame"]||e[a[f]+"CancelRequestAnimationFrame"];c?(e.requestAnimationFrame=c,e.cancelAnimationFrame=
m,g&&(jQuery.fx.timer=function(a){a()&&jQuery.timers.push(a)&&!d&&(d=!0,b())},jQuery.fx.stop=function(){d=!1})):(e.requestAnimationFrame=function(a){var b=(new Date).getTime(),d=Math.max(0,16-(b-f)),c=e.setTimeout(function(){a(b+d)},d);f=b+d;return c},e.cancelAnimationFrame=function(a){clearTimeout(a)})})(jQuery);e.Foundation={name:"Foundation",version:"5.5.0",media_queries:{small:a(".foundation-mq-small").css("font-family").replace(/^[\/\\'"]+|(;\s?})+|[\/\\'"]+$/g,""),"small-only":a(".foundation-mq-small-only").css("font-family").replace(/^[\/\\'"]+|(;\s?})+|[\/\\'"]+$/g,
""),medium:a(".foundation-mq-medium").css("font-family").replace(/^[\/\\'"]+|(;\s?})+|[\/\\'"]+$/g,""),"medium-only":a(".foundation-mq-medium-only").css("font-family").replace(/^[\/\\'"]+|(;\s?})+|[\/\\'"]+$/g,""),large:a(".foundation-mq-large").css("font-family").replace(/^[\/\\'"]+|(;\s?})+|[\/\\'"]+$/g,""),"large-only":a(".foundation-mq-large-only").css("font-family").replace(/^[\/\\'"]+|(;\s?})+|[\/\\'"]+$/g,""),xlarge:a(".foundation-mq-xlarge").css("font-family").replace(/^[\/\\'"]+|(;\s?})+|[\/\\'"]+$/g,
""),"xlarge-only":a(".foundation-mq-xlarge-only").css("font-family").replace(/^[\/\\'"]+|(;\s?})+|[\/\\'"]+$/g,""),xxlarge:a(".foundation-mq-xxlarge").css("font-family").replace(/^[\/\\'"]+|(;\s?})+|[\/\\'"]+$/g,"")},stylesheet:c("<style></style>").appendTo("head")[0].sheet,global:{namespace:l},init:function(b,d,f,c,m){f=[b,f,c,m];c=[];this.rtl=/rtl/i.test(a("html").attr("dir"));this.scope=b||this.scope;this.set_namespace();if(d&&"string"===typeof d&&!/reflow/i.test(d))this.libs.hasOwnProperty(d)&&
c.push(this.init_lib(d,f));else for(var g in this.libs)c.push(this.init_lib(g,d));a(e).load(function(){a(e).trigger("resize.fndtn.clearing").trigger("resize.fndtn.dropdown").trigger("resize.fndtn.equalizer").trigger("resize.fndtn.interchange").trigger("resize.fndtn.joyride").trigger("resize.fndtn.magellan").trigger("resize.fndtn.topbar").trigger("resize.fndtn.slider")});return b},init_lib:function(a,b){if(this.libs.hasOwnProperty(a)){this.patch(this.libs[a]);if(b&&b.hasOwnProperty(a))return"undefined"!==
typeof this.libs[a].settings?c.extend(!0,this.libs[a].settings,b[a]):"undefined"!==typeof this.libs[a].defaults&&c.extend(!0,this.libs[a].defaults,b[a]),this.libs[a].init.apply(this.libs[a],[this.scope,b[a]]);b=b instanceof Array?b:Array(b);return this.libs[a].init.apply(this.libs[a],b)}return function(){}},patch:function(a){a.scope=this.scope;a.namespace=this.global.namespace;a.rtl=this.rtl;a.data_options=this.utils.data_options;a.attr_name=b;a.add_namespace=d;a.bindings=f;a.S=this.utils.S},inherit:function(a,
b){for(var d=b.split(" "),f=d.length;f--;)this.utils.hasOwnProperty(d[f])&&(a[d[f]]=this.utils[d[f]])},set_namespace:function(){var a=this.global.namespace===l?c(".foundation-data-attribute-namespace").css("font-family"):this.global.namespace;this.global.namespace=a===l||/false/i.test(a)?"":a},libs:{},utils:{S:a,throttle:function(a,b){var d=null;return function(){var f=this,c=arguments;null==d&&(d=setTimeout(function(){a.apply(f,c);d=null},b))}},debounce:function(a,b,d){var f,c;return function(){var e=
this,m=arguments,g=d&&!f;clearTimeout(f);f=setTimeout(function(){f=null;d||(c=a.apply(e,m))},b);g&&(c=a.apply(e,m));return c}},data_options:function(a,b){function d(a){return!isNaN(a-0)&&null!==a&&""!==a&&!1!==a&&!0!==a}function f(a){return"string"===typeof a?c.trim(a):a}b=b||"options";var e={},m,g,l;m=function(a){var d=Foundation.global.namespace;return 0<d.length?a.data(d+"-"+b):a.data(b)}(a);if("object"===typeof m)return m;l=(m||":").split(";");for(m=l.length;m--;)g=l[m].split(":"),g=[g[0],g.slice(1).join(":")],
/true/i.test(g[1])&&(g[1]=!0),/false/i.test(g[1])&&(g[1]=!1),d(g[1])&&(-1===g[1].indexOf(".")?g[1]=parseInt(g[1],10):g[1]=parseFloat(g[1])),2===g.length&&0<g[0].length&&(e[f(g[0])]=f(g[1]));return e},register_media:function(a,b){if(Foundation.media_queries[a]===l){c("head").append('<meta class="'+b+'"/>');var d=Foundation.media_queries,f=c("."+b).css("font-family");if("string"===typeof f||f instanceof String)f=f.replace(/^['\\/"]+|(;\s?})+|['\\/"]+$/g,"");d[a]=f}},add_custom_rule:function(a,b){b===
l&&Foundation.stylesheet?Foundation.stylesheet.insertRule(a,Foundation.stylesheet.cssRules.length):Foundation.media_queries[b]!==l&&Foundation.stylesheet.insertRule("@media "+Foundation.media_queries[b]+"{ "+a+" }")},image_loaded:function(a,b){var d=this,f=a.length;0===f&&b(a);a.each(function(){m(d.S(this),function(){--f;0===f&&b(a)})})},random_str:function(){this.fidx||(this.fidx=0);this.prefix=this.prefix||[this.name||"F",(+new Date).toString(36)].join("-");return this.prefix+(this.fidx++).toString(36)},
match:function(a){return e.matchMedia(a).matches},is_small_up:function(){return this.match(Foundation.media_queries.small)},is_medium_up:function(){return this.match(Foundation.media_queries.medium)},is_large_up:function(){return this.match(Foundation.media_queries.large)},is_xlarge_up:function(){return this.match(Foundation.media_queries.xlarge)},is_xxlarge_up:function(){return this.match(Foundation.media_queries.xxlarge)},is_small_only:function(){return!this.is_medium_up()&&!this.is_large_up()&&
!this.is_xlarge_up()&&!this.is_xxlarge_up()},is_medium_only:function(){return this.is_medium_up()&&!this.is_large_up()&&!this.is_xlarge_up()&&!this.is_xxlarge_up()},is_large_only:function(){return this.is_medium_up()&&this.is_large_up()&&!this.is_xlarge_up()&&!this.is_xxlarge_up()},is_xlarge_only:function(){return this.is_medium_up()&&this.is_large_up()&&this.is_xlarge_up()&&!this.is_xxlarge_up()},is_xxlarge_only:function(){return this.is_medium_up()&&this.is_large_up()&&this.is_xlarge_up()&&this.is_xxlarge_up()}}};
c.fn.foundation=function(){var a=Array.prototype.slice.call(arguments,0);return this.each(function(){Foundation.init.apply(Foundation,[this].concat(a));return this})}})(jQuery,window,window.document);
(function(c,e,g,l){Foundation.libs.dropdown={name:"dropdown",version:"5.5.0",settings:{active_class:"open",disabled_class:"disabled",mega_class:"mega",align:"bottom",is_hover:!1,hover_timeout:150,opened:function(){},closed:function(){}},init:function(a,b,d){Foundation.inherit(this,"throttle");c.extend(!0,this.settings,b,d);this.bindings(b,d)},events:function(a){var b=this,d=b.S;d(this.scope).off(".dropdown").on("click.fndtn.dropdown","["+this.attr_name()+"]",function(a){if(!(d(this).data(b.attr_name(!0)+
"-init")||b.settings).is_hover||Modernizr.touch)a.preventDefault(),d(this).parent("[data-reveal-id]")&&a.stopPropagation(),b.toggle(c(this))}).on("mouseenter.fndtn.dropdown","["+this.attr_name()+"], ["+this.attr_name()+"-content]",function(a){var c=d(this),e;clearTimeout(b.timeout);c.data(b.data_attr())?e=d("#"+c.data(b.data_attr())):(e=c,c=d("["+b.attr_name()+'="'+e.attr("id")+'"]'));var g=c.data(b.attr_name(!0)+"-init")||b.settings;d(a.currentTarget).data(b.data_attr())&&g.is_hover&&b.closeall.call(b);
g.is_hover&&b.open.apply(b,[e,c])}).on("mouseleave.fndtn.dropdown","["+this.attr_name()+"], ["+this.attr_name()+"-content]",function(a){var c=d(this),e;e=c.data(b.data_attr())?c.data(b.data_attr(!0)+"-init")||b.settings:d("["+b.attr_name()+'="'+d(this).attr("id")+'"]').data(b.attr_name(!0)+"-init")||b.settings;b.timeout=setTimeout(function(){c.data(b.data_attr())?e.is_hover&&b.close.call(b,d("#"+c.data(b.data_attr()))):e.is_hover&&b.close.call(b,c)}.bind(this),e.hover_timeout)}).on("click.fndtn.dropdown",
function(a){var e=d(a.target).closest("["+b.attr_name()+"-content]");0<e.find("a").length&&"false"!==e.attr("aria-autoclose")&&b.close.call(b,d("["+b.attr_name()+"-content]"));0<d(a.target).closest("["+b.attr_name()+"]").length||(!d(a.target).data("revealId")&&0<e.length&&(d(a.target).is("["+b.attr_name()+"-content]")||c.contains(e.first()[0],a.target))?a.stopPropagation():b.close.call(b,d("["+b.attr_name()+"-content]")))}).on("opened.fndtn.dropdown","["+b.attr_name()+"-content]",function(){b.settings.opened.call(this)}).on("closed.fndtn.dropdown",
"["+b.attr_name()+"-content]",function(){b.settings.closed.call(this)});d(e).off(".dropdown").on("resize.fndtn.dropdown",b.throttle(function(){b.resize.call(b)},50));this.resize()},close:function(a){var b=this;a.each(function(){(c("["+b.attr_name()+"="+a[0].id+"]")||c("aria-controls="+a[0].id+"]")).attr("aria-expanded","false");b.S(this).hasClass(b.settings.active_class)&&(b.S(this).css(Foundation.rtl?"right":"left","-99999px").attr("aria-hidden","true").removeClass(b.settings.active_class).prev("["+
b.attr_name()+"]").removeClass(b.settings.active_class).removeData("target"),b.S(this).trigger("closed").trigger("closed.fndtn.dropdown",[a]))});a.removeClass("f-open-"+this.attr_name(!0))},closeall:function(){var a=this;c.each(a.S(".f-open-"+this.attr_name(!0)),function(){a.close.call(a,a.S(this))})},open:function(a,b){this.css(a.addClass(this.settings.active_class),b);a.prev("["+this.attr_name()+"]").addClass(this.settings.active_class);a.data("target",b.get(0)).trigger("opened").trigger("opened.fndtn.dropdown",
[a,b]);a.attr("aria-hidden","false");b.attr("aria-expanded","true");a.focus();a.addClass("f-open-"+this.attr_name(!0))},data_attr:function(){return 0<this.namespace.length?this.namespace+"-"+this.name:this.name},toggle:function(a){if(!a.hasClass(this.settings.disabled_class)){var b=this.S("#"+a.data(this.data_attr()));0!==b.length&&(this.close.call(this,this.S("["+this.attr_name()+"-content]").not(b)),b.hasClass(this.settings.active_class)?(this.close.call(this,b),b.data("target")!==a.get(0)&&this.open.call(this,
b,a)):this.open.call(this,b,a))}},resize:function(){var a=this.S("["+this.attr_name()+"-content].open"),b=this.S("["+this.attr_name()+'="'+a.attr("id")+'"]');a.length&&b.length&&this.css(a,b)},css:function(a,b){var d=Math.max((b.width()-a.width())/2,8),c=b.data(this.attr_name(!0)+"-init")||this.settings;this.clear_idx();this.small()?(c=this.dirs.bottom.call(a,b,c),a.attr("style","").removeClass("drop-left drop-right drop-top").css({position:"absolute",width:"95%","max-width":"none",top:c.top}),a.css(Foundation.rtl?
"right":"left",d)):this.style(a,b,c);return a},style:function(a,b,d){b=c.extend({position:"absolute"},this.dirs[d.align].call(a,b,d));a.attr("style","").css(b)},dirs:{_base:function(a){var b=this.offsetParent().offset(),d=a.offset();d.top-=b.top;d.left-=b.left;d.missRight=!1;d.missTop=!1;d.missLeft=!1;d.leftRightFlag=!1;b=g.getElementsByClassName("row")[0]?g.getElementsByClassName("row")[0].clientWidth:e.outerWidth;b=(e.outerWidth-b)/2;this.hasClass("mega")||(a.offset().top<=this.outerHeight()&&(d.missTop=
!0,d.leftRightFlag=!0),a.offset().left+this.outerWidth()>a.offset().left+b&&a.offset().left-b>this.outerWidth()&&(d.missRight=!0,d.missLeft=!1),0>=a.offset().left-this.outerWidth()&&(d.missLeft=!0,d.missRight=!1));return d},top:function(a,b){var d=Foundation.libs.dropdown,c=d.dirs._base.call(this,a);this.addClass("drop-top");1==c.missTop&&(c.top=c.top+a.outerHeight()+this.outerHeight(),this.removeClass("drop-top"));1==c.missRight&&(c.left=c.left-this.outerWidth()+a.outerWidth());(a.outerWidth()<this.outerWidth()||
d.small()||this.hasClass(b.mega_menu))&&d.adjust_pip(this,a,b,c);return Foundation.rtl?{left:c.left-this.outerWidth()+a.outerWidth(),top:c.top-this.outerHeight()}:{left:c.left,top:c.top-this.outerHeight()}},bottom:function(a,b){var d=Foundation.libs.dropdown,c=d.dirs._base.call(this,a);1==c.missRight&&(c.left=c.left-this.outerWidth()+a.outerWidth());(a.outerWidth()<this.outerWidth()||d.small()||this.hasClass(b.mega_menu))&&d.adjust_pip(this,a,b,c);return d.rtl?{left:c.left-this.outerWidth()+a.outerWidth(),
top:c.top+a.outerHeight()}:{left:c.left,top:c.top+a.outerHeight()}},left:function(a,b){var d=Foundation.libs.dropdown.dirs._base.call(this,a);this.addClass("drop-left");1==d.missLeft&&(d.left+=this.outerWidth(),d.top+=a.outerHeight(),this.removeClass("drop-left"));return{left:d.left-this.outerWidth(),top:d.top}},right:function(a,b){var d=Foundation.libs.dropdown.dirs._base.call(this,a);this.addClass("drop-right");1==d.missRight?(d.left-=this.outerWidth(),d.top+=a.outerHeight(),this.removeClass("drop-right")):
d.triggeredRight=!0;var c=Foundation.libs.dropdown;(a.outerWidth()<this.outerWidth()||c.small()||this.hasClass(b.mega_menu))&&c.adjust_pip(this,a,b,d);return{left:d.left+a.outerWidth(),top:d.top}}},adjust_pip:function(a,b,d,c){var e=Foundation.stylesheet,h=8;a.hasClass(d.mega_class)?h=c.left+b.outerWidth()/2-8:this.small()&&(h+=c.left-8);this.rule_idx=e.cssRules.length;b=".f-dropdown.open:before";d=".f-dropdown.open:after";var g="left: "+h+"px;",h="left: "+(h-1)+"px;";1==c.missRight&&(h=a.outerWidth()-
23,b=".f-dropdown.open:before",d=".f-dropdown.open:after",g="left: "+h+"px;",h="left: "+(h-1)+"px;");1==c.triggeredRight&&(b=".f-dropdown.open:before",d=".f-dropdown.open:after",g="left:-12px;",h="left:-14px;");e.insertRule?(e.insertRule([b,"{",g,"}"].join(" "),this.rule_idx),e.insertRule([d,"{",h,"}"].join(" "),this.rule_idx+1)):(e.addRule(b,g,this.rule_idx),e.addRule(d,h,this.rule_idx+1))},clear_idx:function(){var a=Foundation.stylesheet;"undefined"!==typeof this.rule_idx&&(a.deleteRule(this.rule_idx),
a.deleteRule(this.rule_idx),delete this.rule_idx)},small:function(){return matchMedia(Foundation.media_queries.small).matches&&!matchMedia(Foundation.media_queries.medium).matches},off:function(){this.S(this.scope).off(".fndtn.dropdown");this.S("html, body").off(".fndtn.dropdown");this.S(e).off(".fndtn.dropdown");this.S("[data-dropdown-content]").off(".fndtn.dropdown")},reflow:function(){}}})(jQuery,window,window.document);
(function(c,e,g,l){Foundation.libs.slider={name:"slider",version:"5.5.0",settings:{start:0,end:100,step:1,precision:null,initial:null,display_selector:"",vertical:!1,trigger_input_change:!1,on_change:function(){}},cache:{},init:function(a,b,d){Foundation.inherit(this,"throttle");this.bindings(b,d);this.reflow()},events:function(){var a=this;c(this.scope).off(".slider").on("mousedown.fndtn.slider touchstart.fndtn.slider pointerdown.fndtn.slider","["+a.attr_name()+"]:not(.disabled, [disabled]) .range-slider-handle",
function(b){a.cache.active||(b.preventDefault(),a.set_active_slider(c(b.target)))}).on("mousemove.fndtn.slider touchmove.fndtn.slider pointermove.fndtn.slider",function(b){if(a.cache.active)if(b.preventDefault(),c.data(a.cache.active[0],"settings").vertical){var d=0;b.pageY||(d=e.scrollY);a.calculate_position(a.cache.active,a.get_cursor_position(b,"y")+d)}else a.calculate_position(a.cache.active,a.get_cursor_position(b,"x"))}).on("mouseup.fndtn.slider touchend.fndtn.slider pointerup.fndtn.slider",
function(b){a.remove_active_slider()}).on("change.fndtn.slider",function(b){a.settings.on_change()});a.S(e).on("resize.fndtn.slider",a.throttle(function(b){a.reflow()},300))},get_cursor_position:function(a,b){var d="page"+b.toUpperCase(),c="client"+b.toUpperCase(),e;"undefined"!==typeof a[d]?e=a[d]:"undefined"!==typeof a.originalEvent[c]?e=a.originalEvent[c]:a.originalEvent.touches&&a.originalEvent.touches[0]&&"undefined"!==typeof a.originalEvent.touches[0][c]?e=a.originalEvent.touches[0][c]:a.currentPoint&&
"undefined"!==typeof a.currentPoint[b]&&(e=a.currentPoint[b]);return e},set_active_slider:function(a){this.cache.active=a},remove_active_slider:function(){this.cache.active=null},calculate_position:function(a,b){var d=this,f=c.data(a[0],"settings");c.data(a[0],"handle_l");c.data(a[0],"handle_o");var e=c.data(a[0],"bar_l"),h=c.data(a[0],"bar_o");requestAnimationFrame(function(){var c;c=Foundation.rtl&&!f.vertical?d.limit_to((h+e-b)/e,0,1):d.limit_to((b-h)/e,0,1);c=f.vertical?1-c:c;c=d.normalized_value(c,
f.start,f.end,f.step,f.precision);d.set_ui(a,c)})},set_ui:function(a,b){var d=c.data(a[0],"settings"),f=c.data(a[0],"handle_l"),e=c.data(a[0],"bar_l"),h=this.normalized_percentage(b,d.start,d.end),g=h*(e-f)-1,h=100*h,k=a.parent(),l=a.parent().children("input[type=hidden]");Foundation.rtl&&!d.vertical&&(g=-g);g=d.vertical?-g+e-f+1:g;this.set_translate(a,g,d.vertical);d.vertical?a.siblings(".range-slider-active-segment").css("height",h+"%"):a.siblings(".range-slider-active-segment").css("width",h+"%");
k.attr(this.attr_name(),b).trigger("change").trigger("change.fndtn.slider");l.val(b);d.trigger_input_change&&l.trigger("change");a[0].hasAttribute("aria-valuemin")||a.attr({"aria-valuemin":d.start,"aria-valuemax":d.end});a.attr("aria-valuenow",b);""!=d.display_selector&&c(d.display_selector).each(function(){this.hasOwnProperty("value")?c(this).val(b):c(this).text(b)})},normalized_percentage:function(a,b,d){return Math.min(1,(a-b)/(d-b))},normalized_value:function(a,b,d,c,e){a*=d-b;return((a-a%c)/
c*c+(a%c>=.5*c?c:0)+b).toFixed(e)},set_translate:function(a,b,d){d?c(a).css("-webkit-transform","translateY("+b+"px)").css("-moz-transform","translateY("+b+"px)").css("-ms-transform","translateY("+b+"px)").css("-o-transform","translateY("+b+"px)").css("transform","translateY("+b+"px)"):c(a).css("-webkit-transform","translateX("+b+"px)").css("-moz-transform","translateX("+b+"px)").css("-ms-transform","translateX("+b+"px)").css("-o-transform","translateX("+b+"px)").css("transform","translateX("+b+"px)")},
limit_to:function(a,b,d){return Math.min(Math.max(a,b),d)},initialize_settings:function(a){var b=c.extend({},this.settings,this.data_options(c(a).parent())),d;null===b.precision&&(d=(""+b.step).match(/\.([\d]*)/),b.precision=d&&d[1]?d[1].length:0);b.vertical?(c.data(a,"bar_o",c(a).parent().offset().top),c.data(a,"bar_l",c(a).parent().outerHeight()),c.data(a,"handle_o",c(a).offset().top),c.data(a,"handle_l",c(a).outerHeight())):(c.data(a,"bar_o",c(a).parent().offset().left),c.data(a,"bar_l",c(a).parent().outerWidth()),
c.data(a,"handle_o",c(a).offset().left),c.data(a,"handle_l",c(a).outerWidth()));c.data(a,"bar",c(a).parent());c.data(a,"settings",b)},set_initial_position:function(a){var b=c.data(a.children(".range-slider-handle")[0],"settings"),b="number"!=typeof b.initial||isNaN(b.initial)?Math.floor(.5*(b.end-b.start)/b.step)*b.step+b.start:b.initial;a=a.children(".range-slider-handle");this.set_ui(a,b)},set_value:function(a){var b=this;c("["+b.attr_name()+"]",this.scope).each(function(){c(this).attr(b.attr_name(),
a)});c(this.scope).attr(b.attr_name())&&c(this.scope).attr(b.attr_name(),a);b.reflow()},reflow:function(){var a=this;a.S("["+this.attr_name()+"]").each(function(){var b=c(this).children(".range-slider-handle")[0],d=c(this).attr(a.attr_name());a.initialize_settings(b);d?a.set_ui(c(b),parseFloat(d)):a.set_initial_position(c(this))})}}})(jQuery,window,window.document);
(function(c,e,g,l){Foundation.libs.tab={name:"tab",version:"5.5.0",settings:{active_class:"active",callback:function(){},deep_linking:!1,scroll_to_content:!0,is_hover:!1},default_tab_hashes:[],init:function(a,b,d){var c=this;a=this.S;this.bindings(b,d);this.handle_location_hash_change();a("["+this.attr_name()+"] > .active > a",this.scope).each(function(){c.default_tab_hashes.push(this.hash)})},events:function(){var a=this,b=this.S,d=function(d){if(!b(this).closest("["+a.attr_name()+"]").data(a.attr_name(!0)+
"-init").is_hover||Modernizr.touch)d.preventDefault(),d.stopPropagation(),a.toggle_active_tab(b(this).parent())};b(this.scope).off(".tab").on("focus.fndtn.tab","["+this.attr_name()+"] > * > a",d).on("click.fndtn.tab","["+this.attr_name()+"] > * > a",d).on("mouseenter.fndtn.tab","["+this.attr_name()+"] > * > a",function(d){b(this).closest("["+a.attr_name()+"]").data(a.attr_name(!0)+"-init").is_hover&&a.toggle_active_tab(b(this).parent())});b(e).on("hashchange.fndtn.tab",function(b){b.preventDefault();
a.handle_location_hash_change()})},handle_location_hash_change:function(){var a=this,b=this.S;b("["+this.attr_name()+"]",this.scope).each(function(){var d=b(this).data(a.attr_name(!0)+"-init");if(d.deep_linking)if(d=d.scroll_to_content?a.scope.location.hash:a.scope.location.hash.replace("fndtn-",""),""!=d){var f=b(d);f.hasClass("content")&&f.parent().hasClass("tabs-content")?a.toggle_active_tab(c("["+a.attr_name()+"] > * > a[href="+d+"]").parent()):(f=f.closest(".content").attr("id"),f!=l&&a.toggle_active_tab(c("["+
a.attr_name()+"] > * > a[href=#"+f+"]").parent(),d))}else for(d=0;d<a.default_tab_hashes.length;d++)a.toggle_active_tab(c("["+a.attr_name()+"] > * > a[href="+a.default_tab_hashes[d]+"]").parent())})},toggle_active_tab:function(a,b){var d=this.S,f=a.closest("["+this.attr_name()+"]"),m=a.find("a"),h="#"+a.children("a").first().attr("href").split("#")[1],p=d(h),k=a.siblings(),n=f.data(this.attr_name(!0)+"-init");d(this).data(this.data_attr("tab-content"))&&(h="#"+d(this).data(this.data_attr("tab-content")).split("#")[1],
p=d(h));n.deep_linking&&(n.scroll_to_content?(e.location.hash=b||h,b==l||b==h?a.parent()[0].scrollIntoView():d(h)[0].scrollIntoView()):e.location.hash=b!=l?"fndtn-"+b.replace("#",""):"fndtn-"+h.replace("#",""));a.addClass(n.active_class).triggerHandler("opened");m.attr({"aria-selected":"true",tabindex:0});k.removeClass(n.active_class);k.find("a").attr({"aria-selected":"false",tabindex:-1});p.siblings().removeClass(n.active_class).attr({"aria-hidden":"true",tabindex:-1});p.addClass(n.active_class).attr("aria-hidden",
"false").removeAttr("tabindex");n.callback(a);p.triggerHandler("toggled",[a]);f.triggerHandler("toggled",[p]);m.off("keydown").on("keydown",function(a){var b=c(this),d=c(this).parents("li").prev().children('[role="tab"]'),f=c(this).parents("li").next().children('[role="tab"]');switch(a.keyCode){case 37:a=d;break;case 39:a=f;break;default:a=!1}a.length&&(b.attr({tabindex:"-1","aria-selected":null}),a.attr({tabindex:"0","aria-selected":!0}).focus());c('[role="tabpanel"]').attr("aria-hidden","true");
c("#"+c(g.activeElement).attr("href").substring(1)).attr("aria-hidden",null)})},data_attr:function(a){return 0<this.namespace.length?this.namespace+"-"+a:a},off:function(){},reflow:function(){}}})(jQuery,window,window.document);
(function(c,e,g,l){Foundation.libs.topbar={name:"topbar",version:"5.5.0",settings:{index:0,sticky_class:"sticky",custom_back_text:!0,back_text:"Back",mobile_show_parent_link:!0,is_hover:!0,scrolltop:!0,sticky_on:"all"},init:function(a,b,d){Foundation.inherit(this,"add_custom_rule register_media throttle");var f=this;f.register_media("topbar","foundation-mq-topbar");this.bindings(b,d);f.S("["+this.attr_name()+"]",this.scope).each(function(){var a=c(this),b=a.data(f.attr_name(!0)+"-init");f.S("section, .top-bar-section",
this);a.data("index",0);var d=a.parent();d.hasClass("fixed")||f.is_sticky(a,d,b)?(f.settings.sticky_class=b.sticky_class,f.settings.sticky_topbar=a,a.data("height",d.outerHeight()),a.data("stickyoffset",d.offset().top)):a.data("height",a.outerHeight());b.assembled||f.assemble(a);b.is_hover?f.S(".has-dropdown",a).addClass("not-click"):f.S(".has-dropdown",a).removeClass("not-click");f.add_custom_rule(".f-topbar-fixed { padding-top: "+a.data("height")+"px }");d.hasClass("fixed")&&f.S("body").addClass("f-topbar-fixed")})},
is_sticky:function(a,b,d){return(a=b.hasClass(d.sticky_class))&&"all"===d.sticky_on?!0:a&&this.small()&&"small"===d.sticky_on?matchMedia(Foundation.media_queries.small).matches&&!matchMedia(Foundation.media_queries.medium).matches&&!matchMedia(Foundation.media_queries.large).matches:a&&this.medium()&&"medium"===d.sticky_on?matchMedia(Foundation.media_queries.small).matches&&matchMedia(Foundation.media_queries.medium).matches&&!matchMedia(Foundation.media_queries.large).matches:a&&this.large()&&"large"===
d.sticky_on?matchMedia(Foundation.media_queries.small).matches&&matchMedia(Foundation.media_queries.medium).matches&&matchMedia(Foundation.media_queries.large).matches:!1},toggle:function(a){a=a?this.S(a).closest("["+this.attr_name()+"]"):this.S("["+this.attr_name()+"]");var b=a.data(this.attr_name(!0)+"-init"),d=this.S("section, .top-bar-section",a);this.breakpoint()&&(this.rtl?(d.css({right:"0%"}),c(">.name",d).css({right:"100%"})):(d.css({left:"0%"}),c(">.name",d).css({left:"100%"})),this.S("li.moved",
d).removeClass("moved"),a.data("index",0),a.toggleClass("expanded").css("height",""));b.scrolltop?a.hasClass("expanded")?a.parent().hasClass("fixed")&&(b.scrolltop?(a.parent().removeClass("fixed"),a.addClass("fixed"),this.S("body").removeClass("f-topbar-fixed"),e.scrollTo(0,0)):a.parent().removeClass("expanded")):a.hasClass("fixed")&&(a.parent().addClass("fixed"),a.removeClass("fixed"),this.S("body").addClass("f-topbar-fixed")):(this.is_sticky(a,a.parent(),b)&&a.parent().addClass("fixed"),a.parent().hasClass("fixed")&&
(a.hasClass("expanded")?(a.addClass("fixed"),a.parent().addClass("expanded"),this.S("body").addClass("f-topbar-fixed")):(a.removeClass("fixed"),a.parent().removeClass("expanded"),this.update_sticky_positioning())))},timer:null,events:function(a){var b=this,d=this.S;d(this.scope).off(".topbar").on("click.fndtn.topbar","["+this.attr_name()+"] .toggle-topbar",function(a){a.preventDefault();b.toggle(this)}).on("click.fndtn.topbar",'.top-bar .top-bar-section li a[href^="#"],['+this.attr_name()+'] .top-bar-section li a[href^="#"]',
function(a){a=c(this).closest("li");!b.breakpoint()||a.hasClass("back")||a.hasClass("has-dropdown")||b.toggle()}).on("click.fndtn.topbar","["+this.attr_name()+"] li.has-dropdown",function(a){var e=d(this),h=d(a.target),g=e.closest("["+b.attr_name()+"]").data(b.attr_name(!0)+"-init");h.data("revealId")?b.toggle():b.breakpoint()||g.is_hover&&!Modernizr.touch||(a.stopImmediatePropagation(),e.hasClass("hover")?(e.removeClass("hover").find("li").removeClass("hover"),e.parents("li.hover").removeClass("hover")):
(e.addClass("hover"),c(e).siblings().removeClass("hover"),"A"===h[0].nodeName&&h.parent().hasClass("has-dropdown")&&a.preventDefault()))}).on("click.fndtn.topbar","["+this.attr_name()+"] .has-dropdown>a",function(a){if(b.breakpoint()){a.preventDefault();a=d(this);var c=a.closest("["+b.attr_name()+"]"),e=c.find("section, .top-bar-section");a.next(".dropdown").outerHeight();var g=a.closest("li");c.data("index",c.data("index")+1);g.addClass("moved");b.rtl?(e.css({right:-(100*c.data("index"))+"%"}),e.find(">.name").css({right:100*
c.data("index")+"%"})):(e.css({left:-(100*c.data("index"))+"%"}),e.find(">.name").css({left:100*c.data("index")+"%"}));c.css("height",a.siblings("ul").outerHeight(!0)+c.data("height"))}});d(e).off(".topbar").on("resize.fndtn.topbar",b.throttle(function(){b.resize.call(b)},50)).trigger("resize").trigger("resize.fndtn.topbar").load(function(){d(this).trigger("resize.fndtn.topbar")});d("body").off(".topbar").on("click.fndtn.topbar",function(a){0<d(a.target).closest("li").closest("li.hover").length||
d("["+b.attr_name()+"] li.hover").removeClass("hover")});d(this.scope).on("click.fndtn.topbar","["+this.attr_name()+"] .has-dropdown .back",function(a){a.preventDefault();var c=d(this);a=c.closest("["+b.attr_name()+"]");var e=a.find("section, .top-bar-section");a.data(b.attr_name(!0)+"-init");var g=c.closest("li.moved"),c=g.parent();a.data("index",a.data("index")-1);b.rtl?(e.css({right:-(100*a.data("index"))+"%"}),e.find(">.name").css({right:100*a.data("index")+"%"})):(e.css({left:-(100*a.data("index"))+
"%"}),e.find(">.name").css({left:100*a.data("index")+"%"}));0===a.data("index")?a.css("height",""):a.css("height",c.outerHeight(!0)+a.data("height"));setTimeout(function(){g.removeClass("moved")},300)});d(this.scope).find(".dropdown a").focus(function(){c(this).parents(".has-dropdown").addClass("hover")}).blur(function(){c(this).parents(".has-dropdown").removeClass("hover")})},resize:function(){var a=this;a.S("["+this.attr_name()+"]").each(function(){var b=a.S(this),d=b.data(a.attr_name(!0)+"-init"),
c=b.parent("."+a.settings.sticky_class);if(!a.breakpoint()){var e=b.hasClass("expanded");b.css("height","").removeClass("expanded").find("li").removeClass("hover");e&&a.toggle(b)}a.is_sticky(b,c,d)&&(c.hasClass("fixed")?(c.removeClass("fixed"),d=c.offset().top,a.S(g.body).hasClass("f-topbar-fixed")&&(d-=b.data("height")),b.data("stickyoffset",d),c.addClass("fixed")):(d=c.offset().top,b.data("stickyoffset",d)))})},breakpoint:function(){return!matchMedia(Foundation.media_queries.topbar).matches},small:function(){return matchMedia(Foundation.media_queries.small).matches},
medium:function(){return matchMedia(Foundation.media_queries.medium).matches},large:function(){return matchMedia(Foundation.media_queries.large).matches},assemble:function(a){var b=this,d=a.data(this.attr_name(!0)+"-init"),f=b.S("section, .top-bar-section",a);f.detach();b.S(".has-dropdown>a",f).each(function(){var a=b.S(this),f=a.siblings(".dropdown"),e=a.attr("href");f.find(".title.back").length||(e=1==d.mobile_show_parent_link&&e?c('<li class="title back js-generated"><h5><a href="javascript:void(0)"></a></h5></li><li class="parent-link show-for-small-only"><a class="parent-link js-generated" href="'+
e+'">'+a.html()+"</a></li>"):c('<li class="title back js-generated"><h5><a href="javascript:void(0)"></a></h5>'),1==d.custom_back_text?c("h5>a",e).html(d.back_text):c("h5>a",e).html("&laquo; "+a.html()),f.prepend(e))});f.appendTo(a);this.sticky();this.assembled(a)},assembled:function(a){a.data(this.attr_name(!0),c.extend({},a.data(this.attr_name(!0)),{assembled:!0}))},height:function(a){var b=0,d=this;c("> li",a).each(function(){b+=d.S(this).outerHeight(!0)});return b},sticky:function(){var a=this;
this.S(e).on("scroll",function(){a.update_sticky_positioning()})},update_sticky_positioning:function(){var a="."+this.settings.sticky_class,b=this.S(e);if(this.settings.sticky_topbar&&this.is_sticky(this.settings.sticky_topbar,this.settings.sticky_topbar.parent(),this.settings)){var d=this.settings.sticky_topbar.data("stickyoffset");this.S(a).hasClass("expanded")||(b.scrollTop()>d?this.S(a).hasClass("fixed")||(this.S(a).addClass("fixed"),this.S("body").addClass("f-topbar-fixed")):b.scrollTop()<=d&&
this.S(a).hasClass("fixed")&&(this.S(a).removeClass("fixed"),this.S("body").removeClass("f-topbar-fixed")))}},off:function(){this.S(this.scope).off(".fndtn.topbar");this.S(e).off(".fndtn.topbar")},reflow:function(){}}})(jQuery,window,window.document);(function(c,e,g,l){Foundation.libs.topbar={name:"topbar",version:"5.5.0",settings:{index:0,sticky_class:"sticky",custom_back_text:!0,back_text:"Back",mobile_show_parent_link:!0,is_hover:!0,scrolltop:!0,sticky_on:"all"},init:function(a,b,d){Foundation.inherit(this,"add_custom_rule register_media throttle");var f=this;f.register_media("topbar","foundation-mq-topbar");this.bindings(b,d);f.S("["+this.attr_name()+"]",this.scope).each(function(){var a=c(this),b=a.data(f.attr_name(!0)+"-init");f.S("section, .top-bar-section",
this);a.data("index",0);var d=a.parent();d.hasClass("fixed")||f.is_sticky(a,d,b)?(f.settings.sticky_class=b.sticky_class,f.settings.sticky_topbar=a,a.data("height",d.outerHeight()),a.data("stickyoffset",d.offset().top)):a.data("height",a.outerHeight());b.assembled||f.assemble(a);b.is_hover?f.S(".has-dropdown",a).addClass("not-click"):f.S(".has-dropdown",a).removeClass("not-click");f.add_custom_rule(".f-topbar-fixed { padding-top: "+a.data("height")+"px }");d.hasClass("fixed")&&f.S("body").addClass("f-topbar-fixed")})},
is_sticky:function(a,b,d){return(a=b.hasClass(d.sticky_class))&&"all"===d.sticky_on?!0:a&&this.small()&&"small"===d.sticky_on?matchMedia(Foundation.media_queries.small).matches&&!matchMedia(Foundation.media_queries.medium).matches&&!matchMedia(Foundation.media_queries.large).matches:a&&this.medium()&&"medium"===d.sticky_on?matchMedia(Foundation.media_queries.small).matches&&matchMedia(Foundation.media_queries.medium).matches&&!matchMedia(Foundation.media_queries.large).matches:a&&this.large()&&"large"===
d.sticky_on?matchMedia(Foundation.media_queries.small).matches&&matchMedia(Foundation.media_queries.medium).matches&&matchMedia(Foundation.media_queries.large).matches:!1},toggle:function(a){a=a?this.S(a).closest("["+this.attr_name()+"]"):this.S("["+this.attr_name()+"]");var b=a.data(this.attr_name(!0)+"-init"),d=this.S("section, .top-bar-section",a);this.breakpoint()&&(this.rtl?(d.css({right:"0%"}),c(">.name",d).css({right:"100%"})):(d.css({left:"0%"}),c(">.name",d).css({left:"100%"})),this.S("li.moved",
d).removeClass("moved"),a.data("index",0),a.toggleClass("expanded").css("height",""));b.scrolltop?a.hasClass("expanded")?a.parent().hasClass("fixed")&&(b.scrolltop?(a.parent().removeClass("fixed"),a.addClass("fixed"),this.S("body").removeClass("f-topbar-fixed"),e.scrollTo(0,0)):a.parent().removeClass("expanded")):a.hasClass("fixed")&&(a.parent().addClass("fixed"),a.removeClass("fixed"),this.S("body").addClass("f-topbar-fixed")):(this.is_sticky(a,a.parent(),b)&&a.parent().addClass("fixed"),a.parent().hasClass("fixed")&&
(a.hasClass("expanded")?(a.addClass("fixed"),a.parent().addClass("expanded"),this.S("body").addClass("f-topbar-fixed")):(a.removeClass("fixed"),a.parent().removeClass("expanded"),this.update_sticky_positioning())))},timer:null,events:function(a){var b=this,d=this.S;d(this.scope).off(".topbar").on("click.fndtn.topbar","["+this.attr_name()+"] .toggle-topbar",function(a){a.preventDefault();b.toggle(this)}).on("click.fndtn.topbar",'.top-bar .top-bar-section li a[href^="#"],['+this.attr_name()+'] .top-bar-section li a[href^="#"]',
function(a){a=c(this).closest("li");!b.breakpoint()||a.hasClass("back")||a.hasClass("has-dropdown")||b.toggle()}).on("click.fndtn.topbar","["+this.attr_name()+"] li.has-dropdown",function(a){var e=d(this),g=d(a.target),l=e.closest("["+b.attr_name()+"]").data(b.attr_name(!0)+"-init");g.data("revealId")?b.toggle():b.breakpoint()||l.is_hover&&!Modernizr.touch||(a.stopImmediatePropagation(),e.hasClass("hover")?(e.removeClass("hover").find("li").removeClass("hover"),e.parents("li.hover").removeClass("hover")):
(e.addClass("hover"),c(e).siblings().removeClass("hover"),"A"===g[0].nodeName&&g.parent().hasClass("has-dropdown")&&a.preventDefault()))}).on("click.fndtn.topbar","["+this.attr_name()+"] .has-dropdown>a",function(a){if(b.breakpoint()){a.preventDefault();a=d(this);var c=a.closest("["+b.attr_name()+"]"),e=c.find("section, .top-bar-section");a.next(".dropdown").outerHeight();var g=a.closest("li");c.data("index",c.data("index")+1);g.addClass("moved");b.rtl?(e.css({right:-(100*c.data("index"))+"%"}),e.find(">.name").css({right:100*
c.data("index")+"%"})):(e.css({left:-(100*c.data("index"))+"%"}),e.find(">.name").css({left:100*c.data("index")+"%"}));c.css("height",a.siblings("ul").outerHeight(!0)+c.data("height"))}});d(e).off(".topbar").on("resize.fndtn.topbar",b.throttle(function(){b.resize.call(b)},50)).trigger("resize").trigger("resize.fndtn.topbar").load(function(){d(this).trigger("resize.fndtn.topbar")});d("body").off(".topbar").on("click.fndtn.topbar",function(a){0<d(a.target).closest("li").closest("li.hover").length||
d("["+b.attr_name()+"] li.hover").removeClass("hover")});d(this.scope).on("click.fndtn.topbar","["+this.attr_name()+"] .has-dropdown .back",function(a){a.preventDefault();var c=d(this);a=c.closest("["+b.attr_name()+"]");var e=a.find("section, .top-bar-section");a.data(b.attr_name(!0)+"-init");var g=c.closest("li.moved"),c=g.parent();a.data("index",a.data("index")-1);b.rtl?(e.css({right:-(100*a.data("index"))+"%"}),e.find(">.name").css({right:100*a.data("index")+"%"})):(e.css({left:-(100*a.data("index"))+
"%"}),e.find(">.name").css({left:100*a.data("index")+"%"}));0===a.data("index")?a.css("height",""):a.css("height",c.outerHeight(!0)+a.data("height"));setTimeout(function(){g.removeClass("moved")},300)});d(this.scope).find(".dropdown a").focus(function(){c(this).parents(".has-dropdown").addClass("hover")}).blur(function(){c(this).parents(".has-dropdown").removeClass("hover")})},resize:function(){var a=this;a.S("["+this.attr_name()+"]").each(function(){var b=a.S(this),c=b.data(a.attr_name(!0)+"-init"),
e=b.parent("."+a.settings.sticky_class);if(!a.breakpoint()){var l=b.hasClass("expanded");b.css("height","").removeClass("expanded").find("li").removeClass("hover");l&&a.toggle(b)}a.is_sticky(b,e,c)&&(e.hasClass("fixed")?(e.removeClass("fixed"),c=e.offset().top,a.S(g.body).hasClass("f-topbar-fixed")&&(c-=b.data("height")),b.data("stickyoffset",c),e.addClass("fixed")):(c=e.offset().top,b.data("stickyoffset",c)))})},breakpoint:function(){return!matchMedia(Foundation.media_queries.topbar).matches},small:function(){return matchMedia(Foundation.media_queries.small).matches},
medium:function(){return matchMedia(Foundation.media_queries.medium).matches},large:function(){return matchMedia(Foundation.media_queries.large).matches},assemble:function(a){var b=this,d=a.data(this.attr_name(!0)+"-init"),e=b.S("section, .top-bar-section",a);e.detach();b.S(".has-dropdown>a",e).each(function(){var a=b.S(this),e=a.siblings(".dropdown"),f=a.attr("href");e.find(".title.back").length||(f=1==d.mobile_show_parent_link&&f?c('<li class="title back js-generated"><h5><a href="javascript:void(0)"></a></h5></li><li class="parent-link show-for-small-only"><a class="parent-link js-generated" href="'+
f+'">'+a.html()+"</a></li>"):c('<li class="title back js-generated"><h5><a href="javascript:void(0)"></a></h5>'),1==d.custom_back_text?c("h5>a",f).html(d.back_text):c("h5>a",f).html("&laquo; "+a.html()),e.prepend(f))});e.appendTo(a);this.sticky();this.assembled(a)},assembled:function(a){a.data(this.attr_name(!0),c.extend({},a.data(this.attr_name(!0)),{assembled:!0}))},height:function(a){var b=0,d=this;c("> li",a).each(function(){b+=d.S(this).outerHeight(!0)});return b},sticky:function(){var a=this;
this.S(e).on("scroll",function(){a.update_sticky_positioning()})},update_sticky_positioning:function(){var a="."+this.settings.sticky_class,b=this.S(e);if(this.settings.sticky_topbar&&this.is_sticky(this.settings.sticky_topbar,this.settings.sticky_topbar.parent(),this.settings)){var c=this.settings.sticky_topbar.data("stickyoffset");this.S(a).hasClass("expanded")||(b.scrollTop()>c?this.S(a).hasClass("fixed")||(this.S(a).addClass("fixed"),this.S("body").addClass("f-topbar-fixed")):b.scrollTop()<=c&&
this.S(a).hasClass("fixed")&&(this.S(a).removeClass("fixed"),this.S("body").removeClass("f-topbar-fixed")))}},off:function(){this.S(this.scope).off(".fndtn.topbar");this.S(e).off(".fndtn.topbar")},reflow:function(){}}})(jQuery,window,window.document);window.Modernizr=function(c,e,g){function l(a,b){return typeof a===b}function a(a,b){for(var c in a){var d=a[c];if(!~(""+d).indexOf("-")&&n[d]!==g)return"pfx"==b?d:!0}return!1}function b(b,c,d){var e=b.charAt(0).toUpperCase()+b.slice(1),f=(b+" "+C.join(e+" ")+e).split(" ");if(l(c,"string")||l(c,"undefined"))c=a(f,c);else a:{f=(b+" "+D.join(e+" ")+e).split(" "),b=f;for(var h in b)if(e=c[b[h]],e!==g){c=!1===d?b[h]:l(e,"function")?e.bind(d||c):e;break a}c=!1}return c}function d(){h.input=function(a){for(var b=
0,d=a.length;d>b;b++)v[a[b]]=!!(a[b]in q);return v.list&&(v.list=!(!e.createElement("datalist")||!c.HTMLDataListElement)),v}("autocomplete autofocus list placeholder max min multiple pattern required step".split(" "));h.inputtypes=function(a){for(var b,c,d,f=0,h=a.length;h>f;f++)q.setAttribute("type",c=a[f]),(b="text"!==q.type)&&(q.value=w,q.style.cssText="position:absolute;visibility:hidden;",/^range$/.test(c)&&q.style.WebkitAppearance!==g?(p.appendChild(q),d=e.defaultView,b=d.getComputedStyle&&
"textfield"!==d.getComputedStyle(q,null).WebkitAppearance&&0!==q.offsetHeight,p.removeChild(q)):/^(search|tel)$/.test(c)||(b=/^(url|email)$/.test(c)?q.checkValidity&&!1===q.checkValidity():q.value!=w)),E[a[f]]=!!b;return E}("search tel url email datetime date month week time datetime-local number range color".split(" "))}var f,m,h={},p=e.documentElement,k=e.createElement("modernizr"),n=k.style,q=e.createElement("input"),w=":)",B={}.toString,u=" -webkit- -moz- -o- -ms- ".split(" "),C=["Webkit","Moz",
"O","ms"],D=["webkit","moz","o","ms"],k={},E={},v={},x=[],y=x.slice,r=function(a,b,c,d){var f,g,h,k,l=e.createElement("div"),n=e.body,m=n||e.createElement("body");if(parseInt(c,10))for(;c--;)h=e.createElement("div"),h.id=d?d[c]:"modernizr"+(c+1),l.appendChild(h);return f=['&#173;<style id="smodernizr">',a,"</style>"].join(""),l.id="modernizr",(n?l:m).innerHTML+=f,m.appendChild(l),n||(m.style.background="",m.style.overflow="hidden",k=p.style.overflow,p.style.overflow="hidden",p.appendChild(m)),g=b(l,
a),n?l.parentNode.removeChild(l):(m.parentNode.removeChild(m),p.style.overflow=k),!!g},F=function(){var a={select:"input",change:"input",submit:"form",reset:"form",error:"img",load:"img",abort:"img"};return function(b,c){c=c||e.createElement(a[b]||"div");b="on"+b;var d=b in c;return d||(c.setAttribute||(c=e.createElement("div")),c.setAttribute&&c.removeAttribute&&(c.setAttribute(b,""),d=l(c[b],"function"),l(c[b],"undefined")||(c[b]=g),c.removeAttribute(b))),d}}(),z={}.hasOwnProperty;m=l(z,"undefined")||
l(z.call,"undefined")?function(a,b){return b in a&&l(a.constructor.prototype[b],"undefined")}:function(a,b){return z.call(a,b)};Function.prototype.bind||(Function.prototype.bind=function(a){var b=this;if("function"!=typeof b)throw new TypeError;var c=y.call(arguments,1),d=function(){if(this instanceof d){var e=function(){};e.prototype=b.prototype;var e=new e,f=b.apply(e,c.concat(y.call(arguments)));return Object(f)===f?f:e}return b.apply(a,c.concat(y.call(arguments)))};return d});k.flexbox=function(){return b("flexWrap")};
k.flexboxlegacy=function(){return b("boxDirection")};k.canvas=function(){var a=e.createElement("canvas");return!(!a.getContext||!a.getContext("2d"))};k.canvastext=function(){return!(!h.canvas||!l(e.createElement("canvas").getContext("2d").fillText,"function"))};k.webgl=function(){return!!c.WebGLRenderingContext};k.touch=function(){var a;return"ontouchstart"in c||c.DocumentTouch&&e instanceof DocumentTouch?a=!0:r(["@media (",u.join("touch-enabled),("),"modernizr){#modernizr{top:9px;position:absolute}}"].join(""),
function(b){a=9===b.offsetTop}),a};k.geolocation=function(){return"geolocation"in navigator};k.postmessage=function(){return!!c.postMessage};k.websqldatabase=function(){return!!c.openDatabase};k.indexedDB=function(){return!!b("indexedDB",c)};k.hashchange=function(){return F("hashchange",c)&&(e.documentMode===g||7<e.documentMode)};k.history=function(){return!(!c.history||!history.pushState)};k.draganddrop=function(){var a=e.createElement("div");return"draggable"in a||"ondragstart"in a&&"ondrop"in a};
k.websockets=function(){return"WebSocket"in c||"MozWebSocket"in c};k.rgba=function(){n.cssText="background-color:rgba(150,255,150,.5)";return!!~(""+n.backgroundColor).indexOf("rgba")};k.hsla=function(){n.cssText="background-color:hsla(120,40%,100%,.5)";return!!~(""+n.backgroundColor).indexOf("rgba")||!!~(""+n.backgroundColor).indexOf("hsla")};k.multiplebgs=function(){n.cssText="background:url(https://),url(https://),red url(https://)";return/(url\s*\(.*?){3}/.test(n.background)};k.backgroundsize=
function(){return b("backgroundSize")};k.borderimage=function(){return b("borderImage")};k.borderradius=function(){return b("borderRadius")};k.boxshadow=function(){return b("boxShadow")};k.textshadow=function(){return""===e.createElement("div").style.textShadow};k.opacity=function(){var a=u.join("opacity:.55;")+"";n.cssText=a;return/^0.55$/.test(n.opacity)};k.cssanimations=function(){return b("animationName")};k.csscolumns=function(){return b("columnCount")};k.cssgradients=function(){var a=("background-image:-webkit-gradient(linear,left top,right bottom,from(#9f9),to(white));background-image:"+
u.join("linear-gradient(left top,#9f9, white);background-image:")).slice(0,-17);n.cssText=a;return!!~(""+n.backgroundImage).indexOf("gradient")};k.cssreflections=function(){return b("boxReflect")};k.csstransforms=function(){return!!b("transform")};k.csstransforms3d=function(){var a=!!b("perspective");return a&&"webkitPerspective"in p.style&&r("@media (transform-3d),(-webkit-transform-3d){#modernizr{left:9px;position:absolute;height:3px;}}",function(b){a=9===b.offsetLeft&&3===b.offsetHeight}),a};k.csstransitions=
function(){return b("transition")};k.fontface=function(){var a;return r('@font-face {font-family:"font";src:url("https://")}',function(b,c){var d=e.getElementById("smodernizr"),d=(d=d.sheet||d.styleSheet)?d.cssRules&&d.cssRules[0]?d.cssRules[0].cssText:d.cssText||"":"";a=/src/i.test(d)&&0===d.indexOf(c.split(" ")[0])}),a};k.generatedcontent=function(){var a;return r(['#modernizr{font:0/0 a}#modernizr:after{content:"',w,'";visibility:hidden;font:3px/1 a}'].join(""),function(b){a=3<=b.offsetHeight}),
a};k.video=function(){var a=e.createElement("video"),b=!1;try{(b=!!a.canPlayType)&&(b=new Boolean(b),b.ogg=a.canPlayType('video/ogg; codecs="theora"').replace(/^no$/,""),b.h264=a.canPlayType('video/mp4; codecs="avc1.42E01E"').replace(/^no$/,""),b.webm=a.canPlayType('video/webm; codecs="vp8, vorbis"').replace(/^no$/,""))}catch(c){}return b};k.audio=function(){var a=e.createElement("audio"),b=!1;try{(b=!!a.canPlayType)&&(b=new Boolean(b),b.ogg=a.canPlayType('audio/ogg; codecs="vorbis"').replace(/^no$/,
""),b.mp3=a.canPlayType("audio/mpeg;").replace(/^no$/,""),b.wav=a.canPlayType('audio/wav; codecs="1"').replace(/^no$/,""),b.m4a=(a.canPlayType("audio/x-m4a;")||a.canPlayType("audio/aac;")).replace(/^no$/,""))}catch(c){}return b};k.localstorage=function(){try{return localStorage.setItem("modernizr","modernizr"),localStorage.removeItem("modernizr"),!0}catch(a){return!1}};k.sessionstorage=function(){try{return sessionStorage.setItem("modernizr","modernizr"),sessionStorage.removeItem("modernizr"),!0}catch(a){return!1}};
k.webworkers=function(){return!!c.Worker};k.applicationcache=function(){return!!c.applicationCache};k.svg=function(){return!!e.createElementNS&&!!e.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect};k.inlinesvg=function(){var a=e.createElement("div");return a.innerHTML="<svg/>","http://www.w3.org/2000/svg"==(a.firstChild&&a.firstChild.namespaceURI)};k.smil=function(){return!!e.createElementNS&&/SVGAnimate/.test(B.call(e.createElementNS("http://www.w3.org/2000/svg","animate")))};k.svgclippaths=
function(){return!!e.createElementNS&&/SVGClipPath/.test(B.call(e.createElementNS("http://www.w3.org/2000/svg","clipPath")))};for(var A in k)m(k,A)&&(f=A.toLowerCase(),h[f]=k[A](),x.push((h[f]?"":"no-")+f));h.input||d();h.addTest=function(a,b){if("object"==typeof a)for(var c in a)m(a,c)&&h.addTest(c,a[c]);else{if(a=a.toLowerCase(),h[a]!==g)return h;b="function"==typeof b?b():b;p.className+=" "+(b?"":"no-")+a;h[a]=b}return h};n.cssText="";return k=q=null,function(a,b){function c(){var a=t.elements;
return"string"==typeof a?a.split(" "):a}function d(a){var b=r[a[p]];return b||(b={},q++,a[p]=q,r[q]=b),b}function e(a,c,f){if(c||(c=b),l)return c.createElement(a);f||(f=d(c));var g;return g=f.cache[a]?f.cache[a].cloneNode():n.test(a)?(f.cache[a]=f.createElem(a)).cloneNode():f.createElem(a),!g.canHaveChildren||m.test(a)||g.tagUrn?g:f.frag.appendChild(g)}function f(a,b){b.cache||(b.cache={},b.createElem=a.createElement,b.createFrag=a.createDocumentFragment,b.frag=b.createFrag());a.createElement=function(c){return t.shivMethods?
e(c,a,b):b.createElem(c)};a.createDocumentFragment=Function("h,f","return function(){var n=f.cloneNode(),c=n.createElement;h.shivMethods&&("+c().join().replace(/[\w\-]+/g,function(a){return b.createElem(a),b.frag.createElement(a),'c("'+a+'")'})+");return n}")(t,b.frag)}function g(a){a||(a=b);var c=d(a);if(t.shivCSS&&!h&&!c.hasCSS){var e,k=a;e=k.createElement("p");k=k.getElementsByTagName("head")[0]||k.documentElement;e=(e.innerHTML="x<style>article,aside,dialog,figcaption,figure,footer,header,hgroup,main,nav,section{display:block}mark{background:#FF0;color:#000}template{display:none}</style>",
k.insertBefore(e.lastChild,k.firstChild));c.hasCSS=!!e}return l||f(a,c),a}var h,l,k=a.html5||{},m=/^<|^(?:button|map|select|textarea|object|iframe|option|optgroup)$/i,n=/^(?:a|b|code|div|fieldset|h1|h2|h3|h4|h5|h6|i|label|li|ol|p|q|span|strong|style|table|tbody|td|th|tr|ul)$/i,p="_html5shiv",q=0,r={};!function(){try{var a=b.createElement("a");a.innerHTML="<xyz></xyz>";h="hidden"in a;var c;if(!(c=1==a.childNodes.length)){b.createElement("a");var d=b.createDocumentFragment();c="undefined"==typeof d.cloneNode||
"undefined"==typeof d.createDocumentFragment||"undefined"==typeof d.createElement}l=c}catch(e){l=h=!0}}();var t={elements:k.elements||"abbr article aside audio bdi canvas data datalist details dialog figcaption figure footer header hgroup main mark meter nav output progress section summary template time video",version:"3.7.0",shivCSS:!1!==k.shivCSS,supportsUnknownElements:l,shivMethods:!1!==k.shivMethods,type:"default",shivDocument:g,createElement:e,createDocumentFragment:function(a,e){if(a||(a=b),
l)return a.createDocumentFragment();e=e||d(a);for(var f=e.frag.cloneNode(),g=0,h=c(),k=h.length;k>g;g++)f.createElement(h[g]);return f}};a.html5=t;g(b)}(this,e),h._version="2.8.3",h._prefixes=u,h._domPrefixes=D,h._cssomPrefixes=C,h.mq=function(a){var b=c.matchMedia||c.msMatchMedia;if(b)return b(a)&&b(a).matches||!1;var d;return r("@media "+a+" { #modernizr { position: absolute; } }",function(a){d="absolute"==(c.getComputedStyle?getComputedStyle(a,null):a.currentStyle).position}),d},h.hasEvent=F,h.testProp=
function(b){return a([b])},h.testAllProps=b,h.testStyles=r,h.prefixed=function(a,c,d){return c?b(a,c,d):b(a,"pfx")},p.className=p.className.replace(/(^|\s)no-js(\s|$)/,"$1$2")+(" js "+x.join(" ")),h}(this,this.document);(function(){function c(){var a=$(window).scrollTop();e=e.filter(function(b){var c=$(b.selector).offset().top-$(window).height();return c-a<b.threshold||a>c?(b.callback(),!1):!0})}var e=[];window.add_lazy_load_section=function(a,b,c){if($(a).offset()){if(!c||0>c)c=500;e.push({selector:a,callback:b,threshold:c})}};var g=window.epochload;g&&(window.epochload={push:function(a){a()}},g.filter(function(a){a();return!1}));var l=null;$(window).scroll(function(){l=!0});setInterval(function(){l&&(l=!1,c())},
250)})();
$(document).ready(function(){var c=$("#relatedArticles");"undefined"!=typeof c&&c.prepend("<a href='#' id='click_to_next_1' title='\u9ede\u64ca\u770b\u4e0b\u4e00\u7bc7\u6587\u7ae0\uff01' class='click_next'><span style='background-image:url(http://www.epochtimes.com/images/icons/arrow-down-animated1.gif);background-size:44px 79px;display:block;width:45px;height:79px;'></span></a><script type='text/javascript'>$('#click_to_next_1').click(function(){$('html, body').animate({scrollTop: $('#first_bottom').offset().top}, 1000);return false;});\x3c/script>").css("position","relative");
setTimeout(function(){$("#relatedArticles").waypoint(function(c){var g=$("#relatedArticles > li:eq(0)");"undefined"!=typeof g&&(c=window.location.pathname,g=g.find(".newslist").find("a").attr("href"),c!=g?($("#relatedArticles #click_to_next_1").show(),$.get("/next.htm?v=1&url="+g,function(c){$("#bd").append(c)})):(g=$("#relatedArticles > li:eq(1)"),"undefined"!=typeof g&&(g=g.find(".newslist").find("a").attr("href"),c!=g&&($("#relatedArticles #click_to_next_1").show(),$.get("/next.htm?v=1&url="+g,
function(c){$("#bd").append(c)})))),$("#relatedArticles").waypoint("destroy"))},{offset:"35%"})},5E3);c=$(".box2:eq(0)").html();$(".box2:eq(0)").remove();$("#below_article_ad #related").prepend(c);$.fn.laziestloader?$(".imgbox img").laziestloader({threshold:500}):$(".imgbox img").lazyload({effect:"fadeIn"})});
jQuery(document).ready(function(c){var e=c(".cd-top");c(window).scroll(function(){300<c(this).scrollTop()?e.addClass("cd-is-visible"):e.removeClass("cd-is-visible cd-fade-out");1200<c(this).scrollTop()&&e.addClass("cd-fade-out")});e.on("click",function(e){e.preventDefault();c("body,html").animate({scrollTop:0},700)})});
$(document).ready(function(){(function(c,e){window.epochload?epochload.push(function(){add_lazy_load_section(c,e)}):e()})("h1",function(){$.get("/ad/like/likes.htm",function(c){$("body").append(c)})});"undefined"!=typeof $("#closeself")&&$("#closeself").click(function(){window.close()})});
(function(){var c=document.createElement("script");c.async=!0;c.type="text/javascript";c.src=("https:"==document.location.protocol?"https:":"http:")+"//www.googletagservices.com/tag/js/gpt.js";var e=document.getElementsByTagName("script")[0];e.parentNode.insertBefore(c,e)})();googletag.cmd.push(function(){googletag.enableServices()});googletag.cmd.push(function(){sbi_morpheus.callOperator()});
var artcategory=$("meta[name=category-en]").attr("content"),_sf_async_config={uid:57227,domain:"epochtimes.com",useCanonical:!0};_sf_async_config.sections=artcategory;_sf_async_config.authors="";
(function(){function c(){window._sf_endpt=(new Date).getTime();var c=document.createElement("script");c.setAttribute("language","javascript");c.setAttribute("type","text/javascript");c.setAttribute("src","//static.chartbeat.com/js/chartbeat.js");document.body.appendChild(c)}var e=window.onload;window.onload="function"!=typeof window.onload?c:function(){e();c()}})();var roll_mode=$.cookie("djy-roll-mode");"undefined"==typeof roll_mode&&(roll_mode="1");$(function(){$("#bigtitle #encoding").prepend('<a href="#" id="listing1" class="listing">\u6a19\u984c</a><a href="#" id="listing2" class="listing">\u6458\u8981</a>');togglelist(roll_mode)});
$(function(){$("#listing1").click(function(){togglelist(2);return!1});$("#listing2").click(function(){togglelist(1);return!1});var c=0,e;"undefined"!=typeof $("#leftcol")&&(e=$("#leftcol").css("height"),"undefined"!=typeof e&&(c=e.replace(/[^-\d\.]/g,"")));1<c&&(e=$("div#rightcol").css("height").replace(/[^-\d\.]/g,""),c=c-e+400,"undefined"!=typeof $("div.sticky_content")&&($("div.sticky_content").css("position","relative").css("height",c+"px"),$(".sticky_box").fixer({gap:10})))});
function togglelist(c){"1"==c?($(".topbox").show(),$("#artlist .posts").each(function(){$(this).find(".post-content").show();$(this).find(".headingimage").show();$(this).find(".arttitle .post-date").remove()}),$.cookie("djy-roll-mode","1",{path:"/"}),$("#listing2").addClass("current-listing"),$("#listing1").removeClass("current-listing")):($(".topbox").hide(),$("#artlist .posts").each(function(){var c=$(this).find(".post-content").find(".post-date").html();$(this).find(".post-content").hide();$(this).find(".headingimage").hide();
$(this).find(".arttitle .post-date").remove();$(this).find(".arttitle").append('<div class="post-date">'+c+"</div>").css("font-weight","normal");$(".post-date").css("float","right").css("font-size","14px")}),$.cookie("djy-roll-mode","2",{path:"/"}),$("#listing1").addClass("current-listing"),$("#listing2").removeClass("current-listing"))};
